### ISSUE TITLE
Fonts missing, no idea which ones

### ISSUE THREAD

**Issue by jlconlin** [jsec/tmux-gruvbox-light#2]
I've just discovered the Gruvbox colorscheme and I love it. When I tried adding this package using TPM, my status bar now has some glyphs that it can't display (see screenshot).

<img width="703" alt="Screen Shot 2019-09-20 at 10 29 28 AM" src="https://user-images.githubusercontent.com/1275437/65343217-b7afbf80-db91-11e9-96d0-9247b63b870f.png">

What fonts am I missing? (I'm on a Mac.) I'd rather not have to install fonts, but will do it if it isn't too onerous.

**Comment by jsec** [comment]
You'll need to use a powerline-enabled font.

You can find some here:
https://github.com/powerline/fonts

And here:
https://github.com/ryanoasis/nerd-fonts

I believe Nerd Fonts also includes a font patcher if they don't have the font you're looking for.

**Comment by jlconlin** [comment]
I've installed both the Powerline fonts and nerd-fonts, but still seeing the same behavior. Likely, I'll just have to fork your repository and change a few characters.

**Comment by jlconlin** [comment]
I've installed both the Powerline and nerd-fonts (again) and still see the same behavior. Is there something I need to do after installing the fonts? Do I need to tell my terminal which font to use? I'm sorry I'm such a novice about this.

I really wish I could get this to work because I think what you have done looks really good (as do all of your color schemes.) If you have some other ideas, I would be willing to try it out.

**Comment by jlconlin** [comment]
Never mind, I think I figured it out. I had to change the font used by my terminal. `<feeling sheepish>`
